Repository opendifferentialprivacy/smartnoise-sdk, pull requests merged in 2020-03, with the labels that each got.

#137 Bias test
  evaluation/dp_verification.py
  tests/evaluation/test_stochastic.py
Labels: Evaluator

#142 Refreshing notebook and adding p-value in bias test
  evaluation/Differential Privacy Verification.ipynb
  sdk/burdock/evaluation/dp_verification.py
Labels: Evaluator

#149 Eedeleon/allow service deployer to override dataset call stack
  sdk/burdock/client/__init__.py
  sdk/burdock/data/adapters.py
Labels: SWE

#165 policy laplace dpsu
  sdk/opendp/whitenoise/sql/dpsu.py
  tests/sdk/dpsu/test_dpsu.py
Labels: DS
